-- CONTROLE DE QUILOMETRAGEM V3

create table if not exists motoristas (
  id bigint generated by default as identity primary key,
  local_id text not null unique,
  nome text not null,
  ativo boolean default true,
  atualizado_em timestamp with time zone default now(),
  criado_em timestamp with time zone default now()
);

create table if not exists veiculos (
  id bigint generated by default as identity primary key,
  local_id text not null unique,
  nome text not null,
  ativo boolean default true,
  atualizado_em timestamp with time zone default now(),
  criado_em timestamp with time zone default now()
);

create table if not exists quilometragem (
  id bigint generated by default as identity primary key,
  local_id text not null unique,
  status text,
  data_saida date,
  hora_saida time,
  data_chegada date,
  hora_chegada time,
  tempo text,
  fasa text,
  motorista text,
  veiculo text,
  km_inicial numeric,
  km_final numeric,
  km_rodado numeric,
  combustivel numeric,
  tipo_combustivel text,
  atividade text,
  usuario_email text,
  ativo boolean default true,
  atualizado_em timestamp with time zone default now(),
  criado_em timestamp with time zone default now()
);

alter table motoristas enable row level security;
alter table veiculos enable row level security;
alter table quilometragem enable row level security;

drop policy if exists "permitir tudo motoristas" on motoristas;
drop policy if exists "permitir tudo veiculos" on veiculos;
drop policy if exists "permitir tudo quilometragem" on quilometragem;

create policy "permitir tudo motoristas" on motoristas for all using (true) with check (true);
create policy "permitir tudo veiculos" on veiculos for all using (true) with check (true);
create policy "permitir tudo quilometragem" on quilometragem for all using (true) with check (true);
